title: snippet.mengw.io
email: wm@mengw.io
description: Amazing Snippets
url: https://snippet.mengw.io
github_username: WMXPY
theme: minima
repository: WMXPY/snippet.mengw.io
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge
author:
  name: WMXPY
  email: wm@mengw.io
sass:
  sass_dir: _sass
plugins:
  - jekyll-github-metadata
exclude:
  - .jekyll-cache/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
