title: snippet.mengw.io
description: WMXPY's Amazing Snippets
url: https://snippet.mengw.io
github_username:  WMXPY 
author_info: <a href="http://mengw.io/">WMXPY</a>
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
author:
  name: WMXPY